layout_spectrum: 0.02023609
typography_spectrum: 0.2768045
color:
  lightness: 0.2185774
  brandStrength: 0.7421986
  saturation: 0.8977065
  rhythmicContrast: 0.4995613
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
name: Werbeagentur
